{% set name = "xmgrace" %}
{% set version = "8.1.0" %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: {{ environ.get('FEEDSTOCK_ROOT', '../..') }}

build:
  noarch: python
  number: {{ build_number }}
  string: {{ [build_number, ('h' + PKG_HASH), environ.get('GIT_DESCRIBE_HASH', '')]|join('_') }}

  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cdms2
    - genutil

test:
  imports:
    - xmgrace

about:
  home: https://github.com/CDAT/xmgrace
